export const componentDefaults = {
    "background-full-body": {
        "image": "",
        "mobileImage": ""
    },
    "header-section": {
        "title": "Title",
        "subtitle": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        "titleVisible": true,
        "subtitleVisible": true,
        "buttonStyle": "primary",
        "buttonText": "Label",
        "buttonUrl": "",
        "buttonVisible": true,
        "buttonLinkType": "url",
        "buttonId": "",
        "secondaryButtonText": "Label",
        "secondaryButtonUrl": "",
        "secondaryButtonVisible": true,
        "secondaryButtonLinkType": "url",
        "secondaryButtonId": ""
    },
    "header-group": {
        "title": "Title",
        "subtitle": "Category",
        "titleVisible": true,
        "subtitleVisible": true,
        "buttonStyle": "primary",
        "buttonText": "Label",
        "buttonUrl": "",
        "buttonVisible": true,
        "buttonLinkType": "url",
        "buttonId": "",
        "secondaryButtonText": "Label",
        "secondaryButtonUrl": "",
        "secondaryButtonVisible": true,
        "secondaryButtonLinkType": "url",
        "secondaryButtonId": ""
    },
    "hero-terra-banner": {
        "title": "Title",
        "subtitle": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        "titleVisible": true,
        "subtitleVisible": true,
        "buttonStyle": "primary",
        "buttonText": "Label",
        "buttonUrl": "",
        "buttonVisible": true,
        "buttonLinkType": "url",
        "buttonId": "",
        "secondaryButtonText": "Label",
        "secondaryButtonUrl": "",
        "secondaryButtonVisible": true,
        "secondaryButtonLinkType": "url",
        "secondaryButtonId": "",
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": ""
    },
    "footer-terra": {
        "image": "",
        "copyrightText": "Copyright © 2025 all rights reserved",
        "availableAtTitle": "Available at",
        "resourcesTitle": "About Us",
        "socialLinks": [
            {
                "platform": "facebook",
                "url": "",
                "visible": true,
                "id": ""
            },
            {
                "platform": "twitter",
                "url": "",
                "visible": true,
                "id": ""
            },
            {
                "platform": "instagram",
                "url": "",
                "visible": true,
                "id": ""
            },
            {
                "platform": "tiktok",
                "url": "",
                "visible": true,
                "id": ""
            },
            {
                "platform": "youtube",
                "url": "",
                "visible": true,
                "id": ""
            }
        ],
        "availableAtLinks": [
            {
                "label": "marketplace 1",
                "url": "",
                "visible": true,
                "id": "",
                "image": "",
                "imageId": "",
                "linkType": "url",
                "targetDialogId": ""
            },
            {
                "label": "marketplace 2",
                "url": "",
                "visible": true,
                "id": "",
                "image": "",
                "imageId": "",
                "linkType": "url",
                "targetDialogId": ""
            },
            {
                "label": "marketplace 3",
                "url": "",
                "visible": true,
                "id": "",
                "image": "",
                "imageId": "",
                "linkType": "url",
                "targetDialogId": ""
            }
        ],
        "resourceLinks": [
            {
                "label": "Privacy Policy",
                "url": "",
                "visible": true,
                "id": "",
                "linkType": "url",
                "targetDialogId": ""
            },
            {
                "label": "Terms & Condition",
                "url": "",
                "visible": true,
                "id": "",
                "linkType": "url",
                "targetDialogId": ""
            },
            {
                "label": "Contact Us",
                "url": "",
                "visible": true,
                "id": "",
                "linkType": "url",
                "targetDialogId": ""
            }
        ]
    },
    "feature-image-left": {
        "title": "Title",
        "subtitle": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        "titleVisible": true,
        "subtitleVisible": true,
        "buttonStyle": "primary",
        "buttonText": "Label",
        "buttonUrl": "",
        "buttonVisible": true,
        "buttonLinkType": "url",
        "buttonId": "",
        "secondaryButtonText": "Label",
        "secondaryButtonUrl": "",
        "secondaryButtonVisible": true,
        "secondaryButtonLinkType": "url",
        "secondaryButtonId": "",
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": ""
    },
    "feature-image-right": {
        "title": "Title",
        "subtitle": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        "titleVisible": true,
        "subtitleVisible": true,
        "buttonStyle": "primary",
        "buttonText": "Label",
        "buttonUrl": "",
        "buttonVisible": true,
        "buttonLinkType": "url",
        "buttonId": "",
        "secondaryButtonText": "Label",
        "secondaryButtonUrl": "",
        "secondaryButtonVisible": true,
        "secondaryButtonLinkType": "url",
        "secondaryButtonId": "",
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": ""
    },
    "dialog-item-list": {
        "title": "Title",
        "description": "Description",
        "image": "",
        "imageId": "",
        "imageVisible": true,
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "items": [
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            },
            {
                "label": "Label",
                "image": "",
                "url": "",
                "itemId": "",
                "visible": true
            }
        ]
    },
    "dialog-accordion": {
        "title": "Title",
        "description": "Description",
        "image": "",
        "imageId": "",
        "imageVisible": true,
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "items": [
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            {
                "title": "Accordion Title",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            }
        ]
    },
    "dialog-form": {
        "title": "Title",
        "description": "Description",
        "image": "",
        "imageId": "",
        "imageVisible": true,
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "marketingConsentLabel": "I agree to receive information about exciting offers, product updates, and other information from [brand_name] and other Wings brands.",
        "collectionConsentLabel": "I agree to allow Wings to manage my personal data in accordance with the Wings Privacy Policy.",
        "nameVisible": true,
        "emailVisible": true,
        "whatsappVisible": true,
        "genderVisible": true,
        "dobVisible": true,
        "nameFieldId": "name-field",
        "emailFieldId": "email-field",
        "whatsappFieldId": "whatsapp-field",
        "genderFieldId": "gender-field",
        "dobFieldId": "dob-field",
        "marketingConsentId": "marketing-consent",
        "collectionConsentId": "collection-consent"
    },
    "form-personal-data-section": {
        "marketingConsentLabel": "I agree to receive information about exciting offers, product updates, and other information from [brand_name] and other Wings brands.",
        "collectionConsentLabel": "I agree to allow Wings to manage my personal data in accordance with the Wings Privacy Policy.",
        "nameVisible": true,
        "emailVisible": true,
        "whatsappVisible": true,
        "genderVisible": true,
        "dobVisible": true,
        "marketingConsentVisible": true,
        "collectionConsentVisible": true,
        "nameFieldId": "name-field",
        "emailFieldId": "email-field",
        "whatsappFieldId": "whatsapp-field",
        "genderFieldId": "gender-field",
        "dobFieldId": "dob-field",
        "marketingConsentId": "marketing-consent",
        "collectionConsentId": "collection-consent"
    },
    "osm-banner": {
        "title": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        "buttonText": "Label",
        "buttonUrl": "",
        "buttonVisible": true,
        "buttonLinkType": "url",
        "buttonTargetDialogId": "",
        "buttonId": "",
        "isSticky": true,
        "isOverlay": false
    },
    "media-16-9": {
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "fullWidth": false,
        "imageIsPortrait": false,
        "imageMobileRatio": ""
    },
    "media-5-4": {
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "fullWidth": false,
        "imageIsPortrait": false,
        "imageMobileRatio": ""
    },
    "media-4-3": {
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "fullWidth": false,
        "imageIsPortrait": false,
        "imageMobileRatio": ""
    },
    "media-21-9": {
        "image": "",
        "imageUrl": "",
        "imageLinkType": "url",
        "imageTargetDialogId": "",
        "fullWidth": false,
        "imageIsPortrait": false,
        "imageMobileRatio": ""
    },
    "navigation-center": {
        "logo": "",
        "logoVisible": true,
        "logoId": "",
        "menu1Label": "Menu 1",
        "menu1Url": "",
        "menu1LinkType": "url",
        "menu1TargetDialogId": "",
        "menu1Id": "",
        "menu2Label": "Menu 2",
        "menu2Url": "",
        "menu2LinkType": "url",
        "menu2TargetDialogId": "",
        "menu2Id": "",
        "menu3Label": "Menu 3",
        "menu3Url": "",
        "menu3LinkType": "url",
        "menu3TargetDialogId": "",
        "menu3Id": "",
        "menu4Label": "Menu 4",
        "menu4Url": "",
        "menu4LinkType": "url",
        "menu4TargetDialogId": "",
        "menu4Id": "",
        "isSticky": true,
        "isOverlay": false,
        "menuColor": "default"
    },
    "navigation-left": {
        "logo": "",
        "logoVisible": true,
        "logoId": "",
        "menu1Label": "Menu 1",
        "menu1Url": "",
        "menu1LinkType": "url",
        "menu1TargetDialogId": "",
        "menu1Id": "",
        "menu2Label": "Menu 2",
        "menu2Url": "",
        "menu2LinkType": "url",
        "menu2TargetDialogId": "",
        "menu2Id": "",
        "menu3Label": "Menu 3",
        "menu3Url": "",
        "menu3LinkType": "url",
        "menu3TargetDialogId": "",
        "menu3Id": "",
        "menu4Label": "Menu 4",
        "menu4Url": "",
        "menu4LinkType": "url",
        "menu4TargetDialogId": "",
        "menu4Id": "",
        "isSticky": true,
        "isOverlay": false,
        "menuColor": "default"
    },
    "navigation-right": {
        "logo": "",
        "logoVisible": true,
        "logoId": "",
        "menu1Label": "Menu 1",
        "menu1Url": "",
        "menu1LinkType": "url",
        "menu1TargetDialogId": "",
        "menu1Id": "",
        "menu2Label": "Menu 2",
        "menu2Url": "",
        "menu2LinkType": "url",
        "menu2TargetDialogId": "",
        "menu2Id": "",
        "menu3Label": "Menu 3",
        "menu3Url": "",
        "menu3LinkType": "url",
        "menu3TargetDialogId": "",
        "menu3Id": "",
        "menu4Label": "Menu 4",
        "menu4Url": "",
        "menu4LinkType": "url",
        "menu4TargetDialogId": "",
        "menu4Id": "",
        "isSticky": true,
        "isOverlay": false,
        "menuColor": "default"
    },
    "testimonial-terra": {
        "testimonies": [
            {
                "name": "People Name",
                "role": "Role",
                "description": "Lorem Ipsum is simply dummy text of the printing and typesetting.",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "avatar": "",
                "avatarUrl": "",
                "avatarLinkType": "url",
                "avatarTargetDialogId": "",
                "imageVisible": true,
                "avatarVisible": true,
                "cardId": "",
                "visible": true
            },
            {
                "name": "People Name",
                "role": "Role",
                "description": "Lorem Ipsum is simply dummy text of the printing and typesetting.",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "avatar": "",
                "avatarUrl": "",
                "avatarLinkType": "url",
                "avatarTargetDialogId": "",
                "imageVisible": true,
                "avatarVisible": true,
                "cardId": "",
                "visible": true
            },
            {
                "name": "People Name",
                "role": "Role",
                "description": "Lorem Ipsum is simply dummy text of the printing and typesetting.",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "avatar": "",
                "avatarUrl": "",
                "avatarLinkType": "url",
                "avatarTargetDialogId": "",
                "imageVisible": true,
                "avatarVisible": true,
                "cardId": "",
                "visible": true
            },
            {
                "name": "People Name",
                "role": "Role",
                "description": "Lorem Ipsum is simply dummy text of the printing and typesetting.",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "avatar": "",
                "avatarUrl": "",
                "avatarLinkType": "url",
                "avatarTargetDialogId": "",
                "imageVisible": true,
                "avatarVisible": true,
                "cardId": "",
                "visible": true
            }
        ],
        "fullWidth": false
    },
    "scroll-group": {
        "image": "",
        "mobileImage": "",
        "imageIsPortrait": false,
        "imageMobileRatio": "",
        "scrollEffect": "parallax",
        "components": []
    },
    "spacing-small": {},
    "spacing-medium": {},
    "spacing-large": {},
    "product-carousel-terra": {
        "categories": [
            {
                "id": "cat-1",
                "label": "Category 1",
                "visible": true
            },
            {
                "id": "cat-2",
                "label": "Category 2",
                "visible": true
            },
            {
                "id": "cat-3",
                "label": "Category 3",
                "visible": true
            },
            {
                "id": "cat-4",
                "label": "Category 4",
                "visible": true
            }
        ],
        "products": [
            {
                "name": "Product 1",
                "description": "Description 1",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-1",
                "cardId": "p1-0",
                "visible": true
            },
            {
                "name": "Product 1",
                "description": "Description 1",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-1",
                "cardId": "p1-1",
                "visible": true
            },
            {
                "name": "Product 1",
                "description": "Description 1",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-1",
                "cardId": "p1-2",
                "visible": true
            },
            {
                "name": "Product 1",
                "description": "Description 1",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-1",
                "cardId": "p1-3",
                "visible": true
            },
            {
                "name": "Product 2",
                "description": "Description 2",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-2",
                "cardId": "p2-0",
                "visible": true
            },
            {
                "name": "Product 2",
                "description": "Description 2",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-2",
                "cardId": "p2-1",
                "visible": true
            },
            {
                "name": "Product 2",
                "description": "Description 2",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-2",
                "cardId": "p2-2",
                "visible": true
            },
            {
                "name": "Product 2",
                "description": "Description 2",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-2",
                "cardId": "p2-3",
                "visible": true
            },
            {
                "name": "Product 3",
                "description": "Description 3",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-3",
                "cardId": "p3-0",
                "visible": true
            },
            {
                "name": "Product 3",
                "description": "Description 3",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-3",
                "cardId": "p3-1",
                "visible": true
            },
            {
                "name": "Product 3",
                "description": "Description 3",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-3",
                "cardId": "p3-2",
                "visible": true
            },
            {
                "name": "Product 3",
                "description": "Description 3",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-3",
                "cardId": "p3-3",
                "visible": true
            },
            {
                "name": "Product 4",
                "description": "Description 4",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-4",
                "cardId": "p4-0",
                "visible": true
            },
            {
                "name": "Product 4",
                "description": "Description 4",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-4",
                "cardId": "p4-1",
                "visible": true
            },
            {
                "name": "Product 4",
                "description": "Description 4",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-4",
                "cardId": "p4-2",
                "visible": true
            },
            {
                "name": "Product 4",
                "description": "Description 4",
                "image": "",
                "imageUrl": "",
                "imageLinkType": "url",
                "imageTargetDialogId": "",
                "imageVisible": true,
                "buttonUrl": "",
                "buttonLinkType": "url",
                "buttonTargetDialogId": "",
                "buttonVisible": true,
                "categoryId": "cat-4",
                "cardId": "p4-3",
                "visible": true
            }
        ]
    },
    "social-bridge-tiktok": {
        "videos": [
            {
                "videoUrl": "",
                "name": "",
                "description": "",
                "thumbnailUrl": "",
                "fetchedUrl": "",
                "cardId": "",
                "visible": true
            },
            {
                "videoUrl": "",
                "name": "",
                "description": "",
                "thumbnailUrl": "",
                "fetchedUrl": "",
                "cardId": "",
                "visible": true
            },
            {
                "videoUrl": "",
                "name": "",
                "description": "",
                "thumbnailUrl": "",
                "fetchedUrl": "",
                "cardId": "",
                "visible": true
            },
            {
                "videoUrl": "",
                "name": "",
                "description": "",
                "thumbnailUrl": "",
                "fetchedUrl": "",
                "cardId": "",
                "visible": true
            }
        ],
        "fullWidth": false,
        "allowAutoplay": true
    }
};